name: Notion Sync

on:
  schedule:
    # Esegue ogni 5 minuti
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      DATABASES_SRC: ${{ secrets.DATABASES_SRC }}
      DATABASE_HUB: ${{ secrets.DATABASE_HUB }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Notion sync
        run: node index.js
